version: '2'
services:
  db:
    restart: always
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: Welcome@123
    ports:
      - "3306:3306"
    volumes:
      - "../shared/.mysql-data:/var/lib/mysql"

  memcached:
    restart: always
    image: memcached
    ports:
      - "11211:11211"


  web:
    depends_on:
      - 'db'
      - 'memcached'
    build: .
    user: sonu
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      MEMCACHED_HOST: memcached
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/dimelo-twitter
    ports:
      - "3000:3000"


